[package]
name = "mangadex"
description = "Plugin for mangadex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { workspace = true }
interfaces = { workspace = true }