[workspace]
resolver = "2"
members = [
    "plugins/*",
    "interfaces/",
]

[workspace.dependencies]
serde = "1.0"
extism-pdk = "0.3.4"
extism = "0.5.2"
anyhow = "1.0.75"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
interfaces = { path = "./interfaces/" }
